# CVFCrawler

CVFCRAWLER_URLS = None
CVFCRAWLER_SAVEDIR = None
CVFCRAWLER_ALIVE_PROGRESS_TITLE = "Cloning Papers..."
CVFCRAWLER_PARSER = "html.parser"
CVFCRAWLER_SUCCESS_STATUS_CODE = 200

# PaperDoclingParser
PDP_DO_TABLE_STRUCTURE = True
PDP_DO_PICTURE_CLASSIFICATION = False
PDP_DO_PICTURE_DESCRIPTION = False
PDP_RETURN_DICT = True
PDP_RETURN_MARKDOWN = True
PDP_RETURN_HTML = False
PDP_RETURN_DOCTAGS = False
PDP_OUTPUT_DICT_KEY = "dict"
PDP_OUTPUT_MD_KEY = "markdown"
PDP_OUTPUT_HTML_KEY = "html"
PDP_OUTPUT_DOCTAGS_KEY = "doctags"
PDP_DICT_SAVE_PATH = None
PDP_MD_SAVE_PATH = None
PDP_HTML_SAVE_PATH = None
PDP_DOCTAGS_SAVE_PATH = None
PDP_SAVE_DIR = None
PDP_PDF_MAX_FILE_SIZE_MB = 100